const mumaker = require('mumaker');
const config = require('../../config');

const BOT = config.botName || 'JUNE X ULTRA';

async function sendEphoto(sock, msg, link, text) {
    const chatId = msg.key.remoteJid;
    const result = await mumaker.ephoto(link, text);
    if (!result || !result.image) throw new Error('No image received from the API');
    await sock.sendMessage(chatId, {
        image: { url: result.image },
        caption: `GENERATED BY ${BOT}`
    }, { quoted: msg });
}


function ephotoCmd(name, aliases, description, link) {
    return {
        name,
        aliases,
        category: 'ephoto',
        description,
        usage: `.${name} <text>`,
        async execute(sock, msg, args, { reply }) {
            const text = args.join(' ');
            if (!text) return reply(`Example: .${name} Supreme`);
            await sock.sendMessage(msg.key.remoteJid, { react: { text: '🎨', key: msg.key } });
            try {
                await sendEphoto(sock, msg, link, text);
            } catch (e) {
                reply(`❌ Error generating effect: ${e.message}`);
            }
        }
    };
}


module.exports = [
    ephotoCmd(
        'luxurygold', ['goldtext', 'goldfx'],
        'Create a luxury gold text effect',
        'https://en.ephoto360.com/create-a-luxury-gold-text-effect-online-594.html'
    ),
    ephotoCmd(
        'advancedglow', ['aglow'],
        'Create an advanced glow text effect',
        'https://en.ephoto360.com/advanced-glow-effects-74.html'
    ),
    ephotoCmd(
        'blackpinklogo', ['bplogo'],
        'Create a Blackpink logo style text effect',
        'https://en.ephoto360.com/create-blackpink-logo-online-free-607.html'
    ),
    ephotoCmd(
        'blackpinkstyle', ['bpstyle'],
        'Create a Blackpink style text effect',
        'https://en.ephoto360.com/online-blackpink-style-logo-maker-effect-711.html'
    ),
    ephotoCmd(
        'cartoonstyle', ['cartoonfx'],
        'Create a cartoon graffiti text effect',
        'https://en.ephoto360.com/create-a-cartoon-style-graffiti-text-effect-online-668.html'
    ),
    ephotoCmd(
        'deadpool', ['deadpoolfx'],
        'Create a Deadpool neon green text effect',
        'https://en.ephoto360.com/create-light-effects-green-neon-online-429.html'
    ),
    ephotoCmd(
        'effectclouds', ['cloudsfx'],
        'Write text on clouds in the sky',
        'https://en.ephoto360.com/write-text-effect-clouds-in-the-sky-online-619.html'
    ),
    ephotoCmd(
        'flagtext', ['flagfx'],
        'Create a 3D flag text effect',
        'https://en.ephoto360.com/nigeria-3d-flag-text-effect-online-free-753.html'
    ),
    ephotoCmd(
        'freecreate', ['freefx'],
        'Create a free 3D hologram text effect',
        'https://en.ephoto360.com/free-create-a-3d-hologram-text-effect-441.html'
    ),
    ephotoCmd(
        'galaxystyle', ['galaxyfx'],
        'Create a galaxy style name logo',
        'https://en.ephoto360.com/create-galaxy-style-free-name-logo-438.html'
    ),
    ephotoCmd(
        'galaxywallpaper', ['galaxywp'],
        'Create a galaxy wallpaper with your name',
        'https://en.ephoto360.com/create-galaxy-wallpaper-mobile-online-528.html'
    ),
    ephotoCmd(
        'makingneon', ['makeneon'],
        'Create neon light text with galaxy style',
        'https://en.ephoto360.com/making-neon-light-text-effect-with-galaxy-style-521.html'
    ),
    ephotoCmd(
        'matrixfx', [],
        'Create a Matrix text effect (alternative)',
        'https://en.ephoto360.com/matrix-text-effect-154.html'
    ),
    ephotoCmd(
        'royaltext', ['royalfx'],
        'Create a royal text effect',
        'https://en.ephoto360.com/royal-text-effect-online-free-471.html'
    ),
    ephotoCmd(
        'sandfx', [],
        'Write text in sand on a summer beach (alternative)',
        'https://en.ephoto360.com/write-in-sand-summer-beach-online-576.html'
    ),
    ephotoCmd(
        'summerbeach', ['beachfx'],
        'Write text on a summer beach scene',
        'https://en.ephoto360.com/write-in-sand-summer-beach-online-free-595.html'
    ),
    ephotoCmd(
        'topography', ['topofx'],
        'Create a typography pavement text effect',
        'https://en.ephoto360.com/create-typography-text-effect-on-pavement-online-774.html'
    ),
    ephotoCmd(
        'typography', ['typefx'],
        'Create a typography text effect on pavement',
        'https://en.ephoto360.com/create-typography-text-effect-on-pavement-online-774.html'
    ),
    ephotoCmd(
        'flag3dtext', [],
        'Create an American flag 3D text effect',
        'https://en.ephoto360.com/free-online-american-flag-3d-text-effect-generator-725.html'
    ),
    ephotoCmd(
        'glitchtext', [],
        'Create a digital glitch text effect',
        'https://en.ephoto360.com/create-digital-glitch-text-effects-online-767.html'
    ),
    ephotoCmd(
        'dragonball', ['dbztext'],
        'Create a Dragon Ball style text effect',
        'https://en.ephoto360.com/create-dragon-ball-style-text-effects-online-809.html'
    ),
    ephotoCmd(
        'multicoloredneon', ['mcneon'],
        'Create multicolored neon light signature text',
        'https://en.ephoto360.com/create-multicolored-neon-light-signatures-591.html'
    ),
    ephotoCmd(
        'neonglitch', [],
        'Create an impressive neon glitch text effect',
        'https://en.ephoto360.com/create-impressive-neon-glitch-text-effects-online-768.html'
    ),
    ephotoCmd(
        'papercutstyle', ['papercutfx'],
        'Create a multicolor 3D paper cut style text',
        'https://en.ephoto360.com/multicolor-3d-paper-cut-style-text-effect-658.html'
    ),
    ephotoCmd(
        'pixelglitch', [],
        'Create a pixel glitch text effect',
        'https://en.ephoto360.com/create-pixel-glitch-text-effect-online-769.html'
    ),
    ephotoCmd(
        'glowingtext', ['glowtext'],
        'Create a glowing text effect',
        'https://en.ephoto360.com/create-glowing-text-effects-online-706.html'
    ),
    ephotoCmd(
        'gradienttext', ['gradientfx'],
        'Create a 3D gradient text effect',
        'https://en.ephoto360.com/create-3d-gradient-text-effect-online-600.html'
    ),
    ephotoCmd(
        'graffiti', ['graffitifx'],
        'Create a graffiti text effect',
        'https://en.ephoto360.com/cute-girl-painting-graffiti-text-effect-667.html'
    ),
    ephotoCmd(
        'incandescent', ['bulbtext'],
        'Create a text effect with incandescent bulbs',
        'https://en.ephoto360.com/text-effects-incandescent-bulbs-219.html'
    ),
    ephotoCmd(
        'lighteffects', ['lightfx'],
        'Create a green neon light text effect',
        'https://en.ephoto360.com/create-light-effects-green-neon-online-429.html'
    ),
    ephotoCmd(
        'logomaker', ['bearlogo2'],
        'Create a bear logo style text',
        'https://en.ephoto360.com/free-bear-logo-maker-online-673.html'
    ),
    ephotoCmd(
        'royal', ['royal2'],
        'Create a royal logo text effect',
        'https://en.ephoto360.com/royal-text-effect-online-free-471.html'
    ),
    ephotoCmd(
        'textonwetglass', ['wetglass', 'wetfx'],
        'Create a water text effect',
        'https://en.ephoto360.com/create-water-text-effect-online-589.html'
    ),
    ephotoCmd(
        'bear', ['bearlogo'],
        'Create a bear logo with your name',
        'https://en.ephoto360.com/free-bear-logo-maker-online-673.html'
    ),
    ephotoCmd(
        'papercut', ['3dpaper', 'paper3d'],
        'Create a 3D paper cut style text',
        'https://en.ephoto360.com/multicolor-3d-paper-cut-style-text-effect-658.html'
    ),
    ephotoCmd(
        'hologram', ['3dhologram', 'hologram3d'],
        'Create a 3D hologram text effect',
        'https://en.ephoto360.com/free-create-a-3d-hologram-text-effect-441.html'
    ),
];
